### ISSUE TITLE
Where does the section Joint come from in Ldd edit?

### ISSUE THREAD

**Issue by Simmywang** [Vampyr7878/LegoGeometryViewer#2]
Hi, sorry to trouble again.Now I am trying to get some brick  groups in big lego models.Your make groups using RigidSystem and Joint to set parent in LXFML .But I can`t find how to form the Joint section.It is always like the attach file.
[group_test2.zip](https://github.com/Vampyr7878/LegoGeometryViewer/files/4364496/group_test2.zip)

Would you please tell me how to form the Joint,thank you.

**Comment by Vampyr7878** [comment]
Why do you open an issue here? It's not an issue with my code. You should go on some LDD forums for that.

Still I'll try to help you out on this one, You make groups by using Group feature in LDD. Just put out the pieces, select them and go to Goups tab in the toolbox, click "Create Group from selection". I think it will use Group tag in LXFML. Rigid System is used to designate group of pieces that are connected to eachother in a rigid way and Joint is there to show where the hinges are between two rigid systems. In your example pieces are not even connected.

If you realy want a Joint you can always save the file as LXFML and edit it in notpad or notepad++ to put a joint.

**Comment by Simmywang** [comment]
I see,thank you very much.
